org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
kotlin.code.style=official
android.sync.suppressAgpWarnings=BUILD_TOOLS_TOO_LOW
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true
android.builtInKotlin=false
android.newDsl=false