"""Initial backend schema"""

import sqlalchemy as sa
from alembic import op

revision = "0001_backend"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("device_id"),
    )
    op.create_table(
        "devices",
        sa.Column("device_id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("camera_info", sa.JSON(), nullable=False),
        sa.Column("clip_info", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("device_id"),
    )
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_devices_user_id"), ["user_id"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("task_id"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tasks_user_id"), ["user_id"], unique=False)

    op.create_table(
        "task_versions",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("user_input", sa.Text(), nullable=False),
        sa.Column("parsed_definition", sa.JSON(), nullable=False),
        sa.Column("target_subjects", sa.JSON(), nullable=False),
        sa.Column("interaction_direction", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.CheckConstraint("version >= 1"),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.task_id"],
        ),
        sa.PrimaryKeyConstraint("task_id", "version"),
    )
    op.create_table(
        "sessions",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=128), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("task_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("camera_recording_id", sa.String(length=128), nullable=False),
        sa.Column("sync_event", sa.JSON(), nullable=False),
        sa.Column("privacy_pet_only", sa.Boolean(), nullable=False),
        sa.Column("video_file", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("stopped_at", sa.Float(), nullable=True),
        sa.CheckConstraint("status IN ('active', 'completed')"),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.device_id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id", "task_version"],
            ["task_versions.task_id", "task_versions.version"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "candidates",
        sa.Column("candidate_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("task_version", sa.Integer(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("trigger", sa.String(length=80), nullable=False),
        sa.Column("preview_start_time", sa.Float(), nullable=False),
        sa.Column("preview_end_time", sa.Float(), nullable=False),
        sa.Column("file_start_time", sa.Float(), nullable=True),
        sa.Column("file_end_time", sa.Float(), nullable=True),
        sa.Column("video_file", sa.Text(), nullable=True),
        sa.Column("media_status", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("disposition", sa.String(length=20), nullable=False),
        sa.Column("sampled_frames", sa.JSON(), nullable=False),
        sa.Column("event_metadata", sa.JSON(), nullable=False),
        sa.Column("review_result", sa.JSON(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.CheckConstraint("disposition IN ('undecided','kept','ignored')"),
        sa.CheckConstraint("media_status IN ('available','missing')"),
        sa.CheckConstraint(
            "status IN ('pending_review','preliminary_match','confirmed','needs_review','rejected')"
        ),
        sa.CheckConstraint("preview_end_time >= preview_start_time"),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id", "task_version"],
            ["task_versions.task_id", "task_versions.version"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("candidate_id"),
        sa.UniqueConstraint("user_id", "event_id", name="uq_candidate_event"),
    )
    with op.batch_alter_table("candidates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_candidates_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_candidates_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_candidates_user_id"), ["user_id"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.Float(), nullable=False),
        sa.Column("lease_until", sa.Float(), nullable=True),
        sa.Column("lease_token", sa.String(length=36), nullable=True),
        sa.Column("last_error", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.CheckConstraint("status IN ('queued','running','completed','failed','cancelled')"),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.candidate_id"],
        ),
        sa.PrimaryKeyConstraint("job_id"),
        sa.UniqueConstraint("candidate_id", "candidate_revision"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_candidate_id"), ["candidate_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_status"), ["status"], unique=False)

    op.create_table(
        "system_logs",
        sa.Column("log_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_id", sa.String(length=36), nullable=True),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.candidate_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("log_id"),
    )
    with op.batch_alter_table("system_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_system_logs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "task_examples",
        sa.Column("example_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("task_version", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.String(length=36), nullable=False),
        sa.Column("example_type", sa.String(length=16), nullable=False),
        sa.Column("user_annotation", sa.Text(), nullable=False),
        sa.Column("frames", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.CheckConstraint("example_type IN ('positive','negative')"),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.candidate_id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id", "task_version"],
            ["task_versions.task_id", "task_versions.version"],
        ),
        sa.PrimaryKeyConstraint("example_id"),
        sa.UniqueConstraint("candidate_id", "task_version"),
    )
    op.create_table(
        "user_feedback",
        sa.Column("feedback_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.candidate_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("feedback_id"),
        sa.UniqueConstraint("user_id", "request_id"),
    )
    with op.batch_alter_table("user_feedback", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_feedback_candidate_id"), ["candidate_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_feedback_user_id"), ["user_id"], unique=False)

    op.create_table(
        "review_results",
        sa.Column("review_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.candidate_id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.job_id"],
        ),
        sa.PrimaryKeyConstraint("review_id"),
        sa.UniqueConstraint("job_id"),
    )
    with op.batch_alter_table("review_results", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_review_results_candidate_id"), ["candidate_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_results_candidate_id"))

    op.drop_table("review_results")
    with op.batch_alter_table("user_feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_feedback_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_feedback_candidate_id"))

    op.drop_table("user_feedback")
    op.drop_table("task_examples")
    with op.batch_alter_table("system_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_system_logs_user_id"))

    op.drop_table("system_logs")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_jobs_candidate_id"))

    op.drop_table("jobs")
    with op.batch_alter_table("candidates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidates_user_id"))
        batch_op.drop_index(batch_op.f("ix_candidates_status"))
        batch_op.drop_index(batch_op.f("ix_candidates_session_id"))

    op.drop_table("candidates")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))

    op.drop_table("sessions")
    op.drop_table("task_versions")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tasks_user_id"))

    op.drop_table("tasks")
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_devices_user_id"))

    op.drop_table("devices")
    op.drop_table("users")
    # ### end Alembic commands ###
